### PR TITLE
Extension check audit in some directories

### LINKED ISSUE #352: Validation rule: Disallow .yml extension for form configuration files
## Expected behavior
Form configuration files with .yml extension should raise validation rule, as it’s no longer valid / accepted during import / export

## Actual behavior
No warnings are raised during sync / deploy, import fails silently.

## Steps to reproduce the problem
Create form configuration file with `.yml`

## Version

* pos-cli: 4.2.5
* node: 13.6.0
* os: osx 10.15.3

### LINKED ISSUE #353: Validation rule: "_filename.liquid", "filename.liquid" create duplicate partials.
## Expected behavior
Having two different files resolving to the same partial path should result in a warning / error. 

## Actual behavior
You can create two separate files, called `_filename.liquid` and `filename.liquid`.  It’s impossible to determine which file will be used when `include` tag is used.

```liquid
{% include "filename" %}
```

## Steps to reproduce the problem
Create two partials:

`filename.liquid` and `_filename.liquid`

## Version

* pos-cli: 4.2.5
* node: 13.6.0
* os: OSX

### PR DESCRIPTION
**Pull request by Coornail**
Only allow .liquid files in the following directories:
* forms
* form_configurations
* authorization_policies
* notifications

Only allow .yml files in the following directories:
* custom_model_types
* custom_model_schemas
* instance_profile_types
* instance_profile_schemas

Check for liquid files with the same partial paths.

Fixes #352.
Fixes #353.

### CODE REVIEW

**Comment by pavelloz** [comment]
From the list above, i think a lot of them are deprecated. Looking at this could make it more up to date: https://github.com/mdyd-dev/directory-structure/tree/master/app

**Comment by Slashek** [comment]
@pavelloz yes, but we still want to report lack of proper extension

**Comment by pavelloz** [comment]
Then we want to report proper extension in up to date directories that we recommend using

File: lib/audit/extensions.js [hunk 1]
```diff
@@ -0,0 +1,55 @@
+const glob = require('tiny-glob');
+
+const rules = [
+    {
```
Comment (Slashek) [inline lib/audit/extensions.js]: how about adding `.graphql` extension in `graphql` and `graph_queries`?

File: lib/audit/duplicateFile.js [hunk 2]
```diff
@@ -0,0 +1,31 @@
+const glob = require('tiny-glob');
+const fs = require('fs')
+
+const underScorePrefix = /^_*/;
+
+module.exports = {
+    audit: async () => {
+        let results = {};
+
+        files = await glob('app/**/_*.liquid', { filesOnly: true });
```
Comment (pavelloz) [inline lib/audit/duplicateFile.js]: Probably something like this will be more complete for modules, and i think this `_` thing is only partial thing.
```suggestion
        files = await glob('{app,modules}/**/partials/**/_*.liquid', { filesOnly: true });
```

Comment (Coornail) [reply lib/audit/duplicateFile.js]: Makes sense, changed it.

File: lib/audit.js [hunk 3]
```diff
@@ -20,14 +24,10 @@ const printReport = results => {
 };
 
 const run = async () => {
-  return Promise.all([tags.audit(), filters.audit(), detailed.audit()]).then(([tags, filters, detailed]) => {
-    const offences = [...Object.keys(tags), ...Object.keys(filters), ...Object.keys(detailed)].length;
-
+  return Promise.all(auditors.map(auditor => auditor.audit())).then(reports => {
+    const offences = reports.map(report => Object.keys(report)).length;
```
Comment (pavelloz) [inline lib/audit.js]: Seems like unnecessary complication for humans to save characters for computers

File: lib/audit/extensions.js [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+
+module.exports = {
+    audit: async () => {
+        let results = {};
+
+        for (let rule of rules) {
+            for (let dir of rule.directories) {
+                let files;
+                try {
+                    files = await glob(`app/${dir}/**`, {
```
Comment (pavelloz) [inline lib/audit/extensions.js]: This might need expansion for modules as well
